### ISSUE TITLE
Your template is not updating as its missing the terms of service block

### ISSUE THREAD

**Issue by philpott** [Usercentrics/gtm-templates-usercentrics-cmp#2]
https://github.com/Usercentrics/gtm-templates-usercentrics-cmp/blob/2e4db7f3c34243878f3705b598b09cc6d8179f21/template.tpl#L1

Looking at the latest sync status i see that the terms of service section of the TPL file is not present.

https://tagmanager.google.com/gallery/#/template/Usercentrics/gtm-templates-usercentrics-cmp/status

For more info see the help center article. https://developers.google.com/tag-platform/tag-manager/templates/gallery#terms_of_service

**Comment by uc-rdalmas** [comment]
@philpott Issue has been fixed within [this](https://github.com/Usercentrics/gtm-templates-usercentrics-cmp/commit/c6049ccc62b41d669d2f7536235cc80cbec0983b) commit. Please re-check.

**Comment by uc-rdalmas** [comment]
Issue has been fixed.
